### ISSUE TITLE
Export web component prototype methods onto the react component

### ISSUE THREAD

**Issue by craigpetchell** [webcomponents/react-integration#25]
Web component prototype functions are directly callable on the web component, and useful for providing ways for Javascript to interact with the component.

These methods should be exported onto the React component with identical names, though if they conflict with "reserved" react component method names, then perhaps prefix them with "wc_" first.

**Comment by treshugart** [comment]
+1 from me. I've been thinking about doing this for awhile. The current workaround would be to get the `ref` from the React component and call the method there.

**Comment by craigpetchell** [comment]
Yeh, I've been using that workaround.

**Comment by treshugart** [comment]
Implemented in #32.
