### ISSUE TITLE
"stateful" react injection

### ISSUE THREAD

**Issue by timse** [webcomponents/react-integration#43]
I guess this is a very constructed case, but I am wondering about https://github.com/webcomponents/react-integration/blob/master/src/index.js#L30 .

What was the decision for: 
```js
opts = assign(defaults, opts);
```
intead of 
```js
opts = assign({}, defaults, opts);
```

Again one should imagine that if you inject `React` and `ReactDOM` once, it will be injected all the time, however in a very constructed use case we could have some code like this:

```js
const SomeComponent = reactify(SomeWebComponent);

const SomeOtherComponent = reactify(SomeOtherWebComponent);
```

if I were to be mean I could now call `reactifiy` before all those calls like so:
```js
try{
    reactify(null, {React: null, ReactDom: null})
} catch (e){}
```

killing all following calls to reactify as they will no longer have access to React or ReactDOM.

In fact if you remove the `, { ReactDOM: null }` part from this line:  https://github.com/webcomponents/react-integration/blob/master/test/unit/errors.js#L11

the test will still be green, as `React` is still null. Setting `ReactDOM` to null does not cause the `throw` here.

**Comment by treshugart** [comment]
This seems to be to just be an oversight.

**Comment by timse** [comment]
aye :) 👍

**Comment by treshugart** [comment]
Thanks, @timse!

**Comment by timse** [comment]
you are welcome,

one more thought i has was, that now looking at it im wondering if the `object-assign` polyfill is needed. (Probably a very immature optimization given that probably close to 100% of projects have this as a dependency anyways).

so instead of object assigning the options one could do something along the lines of:

```js
const hOP = Object.prototype.hasOwnProperty;

export default function (CustomElement, opts = {}) {
  const React = hOP.call(opts, 'React') ? opts.React : defaults.React;
  const ReactDOM = hOP.call(opts, 'ReactDOM') ? opts.ReactDOM : defaults.ReactDOM;
```
or if falsy check is enought even
```js
export default function (CustomElement, opts = {}) {
  const React = opts.React || defaults.React;
  const ReactDOM = opts.ReactDOM || defaults.ReactDOM;
```


anyways, probably very premature (:

**Comment by treshugart** [comment]
We could have babel transpile it (it transpiles it to `_extends`, but you still have to included the runtime for it, I think). It's a pretty small library, so we're probably fine until full ES6 support lands in the browsers we care about.

**Comment by timse** [comment]
true 👍
