### ISSUE TITLE
Can I use polymer?

### ISSUE THREAD

**Issue by jaichandra** [webcomponents/react-integration#64]
Can I use Polymer elements (paper-elements) with this library? Can someone please share an example.

**Comment by treshugart** [comment]
As the docs state, you can use any library that exports a native custom element constructor (i.e. new CustomElement()). IIRC Polymer 1 has some issues working outside of Polymer, but Polymer 2 should work just fine.

I'm going to close this now, but feel free to re-open or comment if I haven't adequately answered your question.

Thanks!
