### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by fredyagomez** [webcomponents/react-integration#67]
I reactified my webcomponent but I am having troubling passing custom events and DOM elements from my React app to the web component. 

Is there more documentation, examples I can take a look?

For example, it is not clear to me what is needed to implement in MyComponent per information below provided.

// in MyComponent
var event = new Event('customevent');
elem.dispatchEvent(event);

**Comment by fredyagomez** [comment]
@treshugart I am implemented the @skatejs/val approach and I am able to integrate my web-components with React for all types available. Since I see React community growing exponentially it would be ideal to decide pretty soon which library to use moving forward. The only downside I see is the need to import the h() function + use a non-React syntax to make the web component work.

Syntax Example:

const webComponent = h('web-component', { events: { click() { callFunc() } }, attrs: { 'responsive': true, 'selectable': true }, data: this.state.data }, <div>Hi</div>);

**Comment by treshugart** [comment]
@fredyagomez that's a good point re deciding soon. I'm hoping that feedback from people like yourself could help decide that, since you've seen both. I'll put up a link to it from here to gain more visibility.

Re your example provided, you can also pass the custom element constructor to the `h()` function:

```js
h(WebComponent, ...args);
```

**Comment by fredyagomez** [comment]
Sorry for the delay. Yes, your are right. val covers it already. Removing the comment.

**Comment by treshugart** [comment]
I'm not really sure what you're getting at there. You can already do that with val, right?
